(()=>{
  const assetId=new URLSearchParams(location.search).get("id"),inventoryKey="fs-inventory";
  const readInventory=()=>{try{return JSON.parse(localStorage.getItem(inventoryKey)||"[]")}catch{return[]}};
  const saveInventory=items=>localStorage.setItem(inventoryKey,JSON.stringify(items));
  const addParts=parts=>{const inventory=readInventory();parts.forEach(part=>{const item=inventory.find(entry=>entry.partNumber===part.partNumber);if(!item)inventory.push({id:crypto.randomUUID(),quantity:0,cost:0,reorder:0,...part});});saveInventory(inventory)};
  if(assetId==="REC-BAL-02"){
    saveInventory(readInventory().filter(item=>!String(item.partNumber||"").startsWith("FS-HDC-")));
    addParts([
      {partNumber:"FS-H29-001",name:"Single tension cylinder",asset:"Harris 29N Series Cardboard Baler",source:"Harris 29N Series manufacturer data"},
      {partNumber:"FS-H29-002",name:"Auto-tie tier unit",asset:"Harris 29N Series Cardboard Baler",source:"Harris 29N Series manufacturer data"},
      {partNumber:"FS-H29-003",name:"Subfloor inner liner",asset:"Harris 29N Series Cardboard Baler",source:"Harris 29N Series manufacturer data"},
      {partNumber:"FS-H29-004",name:"Ram-bottom liner",asset:"Harris 29N Series Cardboard Baler",source:"Harris 29N Series manufacturer data"}
    ]);
    document.querySelector("#asset-detail").insertAdjacentHTML("beforeend",`<section class="technical-data"><p class="eyebrow">Manufacturer technical data</p><h2>Harris 29N Series Cardboard Baler</h2><div class="technical-grid"><div><strong>Application</strong><span>Folding carton, heavier corrugated trim and shreds, and other heavier packaging and printing materials</span></div><div><strong>Tension system</strong><span>Single tension cylinder with four-way tension channels</span></div><div><strong>Bale tying</strong><span>Pull-through automatic tie; tier unit on castors for inspection and adjustment</span></div><div><strong>Wear system</strong><span>Heavy-construction subfloor with inner liners on the floor and ram bottoms</span></div></div><h3>Parts added to maintenance inventory</h3><p>FS-H29-001 through FS-H29-004 cover the documented tension cylinder, auto-tie tier, subfloor liner, and ram-bottom liner. The prior DC Series parts were removed.</p><p><a href="https://www.harrisamericanco.com/wp-content/uploads/29N-Series-FULL-PG-2025-FINAL-compressed.pdf" target="_blank" rel="noreferrer">Open Harris 29N Series brochure ↗</a></p><p class="source-note">Obtain the baler serial number before ordering model-specific replacement parts.</p></section>`);
    return;
  }
  if(assetId!=="REC-AUG-01")return;
  const obsolete=new Set(["Hydraulic hose and pipe","Hydraulic pump","Ball valve"]);
  saveInventory(readInventory().filter(item=>!(item.asset==="Komar Auger-Pak Trash Auger"&&obsolete.has(item.name))).map(item=>item.asset==="Komar Auger-Pak Trash Auger"?{...item,asset:"Komar EM-15W Auger-Pak (S/N 4643)",source:"Komar EM-15W manufacturer data; S/N 4643"}:item));
  document.querySelector("#asset-detail").insertAdjacentHTML("beforeend",`<section class="technical-data"><p class="eyebrow">Verified equipment identification</p><h2>Komar EM-15W Auger-Pak®</h2><div class="technical-grid"><div><strong>Manufacturer</strong><span>Komar Industries</span></div><div><strong>Model / serial</strong><span>EM-15W · S/N 4643</span></div><div><strong>Drive</strong><span>15 HP all-electric cycloidal drive</span></div><div><strong>Power</strong><span>480 V · 3 phase · 60 Hz</span></div><div><strong>Application</strong><span>Industrial wood waste processing</span></div><div><strong>Accepted materials</strong><span>Pallets, skids, crates, spools, and manufacturing scrap; nails, brackets and bolts pass through</span></div><div><strong>Processing capacity</strong><span>Up to 2 tons per hour; 2–5 standard pallets per charge</span></div><div><strong>Receiving container</strong><span>Standard 40-cubic-yard container</span></div></div><h3>Major maintenance components</h3><ul><li>Solid-lube bearing support system</li><li>Chain and bearing lubrication system</li><li>Solid alloy-steel auger shaft and cast-alloy steel flights</li><li>Hooked auger teeth and stationary breaker bars</li><li>Cycloidal drive</li><li>Container adaptor and ratchet binders</li></ul><h3>Important parts note</h3><p>This EM-15W is all electric. Hydraulic hose, hydraulic pump, and ball-valve entries were removed from its maintenance inventory. Exact replacement pricing is still vendor-quoted against model EM-15W and serial 4643.</p><p class="source-note">Source: Komar EM-15W manufacturer data and site-provided serial number.</p></section>`);
})();
