services:
  - type: web
    name: fixing-spaces-cmms
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 server:app
